### ISSUE TITLE
Fill REST-API in wiki section

### ISSUE THREAD

**Issue by GeloPakDev** [emotional-help-competition/backend#51]
Describe all our REST API endpoint (including pagination and sorting)
For each endpoint, specify input data:
request parameters if needed
request body data if needed (JSON + DTO format)
expected response (JSON + DTO format)
expected HTTP status code

HTTP status code:

200 OK - no errors
400 BAD request - client validation
401 UNAUTHORIZED - access resource without authentication
403 FORBIDDEN - access resource without authorization
404 NOT FOUND - resource not found exception
409 CONFLICT - trying to delete the same resource
500 INTERNAL ERROR - runtime exception

**Comment by maximelyashevich** [comment]
We have implemented Open API documentation - the task can be rejected.
